title: 3A Systems
email: support@3a-systems.ru
description: >-
  Разработка, внедрение и поддержка Open Identity Platform: OpenDJ, OpenAM, OpenIG, OpenIDM 
baseurl: ""
url: "https://www.3a-systems.ru" 
keywords: openam, opendj, openidm, openig, open identity platform, identity management, access management, iam, open source, directory services, identity gateway

# Build settings
# theme: minima
plugins:
  - jekyll-feed

sass:
  style: compressed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
