- sname: OpenDJ
  name: Directory Services
  desc: >-
    Сервис каталогов LDAP v3. Предоставляет высокую производительность (десятки
    тысяч запросов в секунду), доступность и масштабируемость для безопасного
    хранения цифровых учетных данных, организационно штатной структуры
    организаций и данных приложений.
  url: ./ds

- sname: OpenAM
  name: Access Management
  desc: >-
    Контроль доступа: аутентификация, авторизация, single-sign-on, федерация.
    Предоставляет возможность подключения Web сайтов и мобильных приложений к
    единой точке аутентификации, авторизации и SSO (цифровой паспорт - единая
    точка входа в сервисы компании).
  url: ./am

- sname: OpenIG
  name: Identity Gateway
  desc: >-
    Интернет шлюз (реверсивный прокси) контроля доступа к UI и API. Позволяет
    организовывать защищенный доступ к веб приложениям и API путем решения задач
    маршрутизации, аутентификации, авторизации, федерации и расширения профиля.
  url: ./ig

- sname: OpenIDM
  name: Identity Management
  desc: >-
    Управление учетными данными в различных источниках. Позволяет
    синхронизировать, трансформировать, согласовывать учетные данные
    пользователей, прав доступа, устройств, сертификатов и прочих объектов из
    различных источников (Active Directory, LDAP, SQL, SSH, 1C и т.д.)
  url: ./idm
